# Change these first
owner: dprk-org-pl # Your GitHub organization or username, where this repository lives
repo: taeryong # The name of this repository

sites:
  - name: DPRK.org.pl
    url: https://dprk.org.pl
  - name: Juchify.com
    url: https://juchify.com
  - name: Pyonkoma.com
    url: https://pyonkoma.com
  - name: Taedonggang S1
    url: http://taedonggang.dprk.org.pl
  - name: Potonggang S2
    url: http://potonggang.dprk.org.pl
  - name: Tumangang (1) S3
    url: http://tumangang-1.dprk.org.pl
  - name: Tumangang (2) S3
    url: http://tumangang-2.dprk.org.pl

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dprk.org.pl
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Status: Front Czhollima"
  introTitle: "Status stron i serwerów prowadzonych przez Front Czhollima"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
